v0.2.0

diff --git a/bin/ttab b/bin/ttab
--- a/bin/ttab
+++ b/bin/ttab
@@ -1,107 +1,87 @@
 #!/usr/bin/env bash
 
-kTHIS_NAME=$(basename "$BASH_SOURCE")
+kTHIS_HOMEPAGE='https://github.com/mklement0/ttab'
+kTHIS_NAME=${BASH_SOURCE##*/}
+kTHIS_VERSION='v0.2.0' # NOTE: This assignment is automatically updated by `make version VER=<newVer>` - DO keep the 'v' prefix.
 
-# Helper function for exiting with error message due to runtime error.
-#   die [errMsg [exitCode]]
-# Default error message states context and indicates that execution is aborted. Default exit code is 1.
-# Prefix for context is always prepended.
-# Note: An error message is *always* printed; if you just want to exit with a specific code silently, use `exit n` directly.
-die() {
-    echo "$kTHIS_NAME: ERROR: ${1:-"ABORTING due to unexpected error."}" 1>&2
-    exit ${2:-1} # Note: If the argument is non-numeric, the shell prints a warning and uses exit code 255.
+unset CDPATH  # To prevent unexpected `cd` behavior.
+
+# --- Begin: STANDARD HELPER FUNCTIONS
+
+die() { echo "$kTHIS_NAME: ERROR: ${1:-"ABORTING due to unexpected error."}" 1>&2; exit ${2:-1}; }
+dieSyntax() { echo "$kTHIS_NAME: ARGUMENT ERROR: ${1:-"Invalid argument(s) specified."} Use -h for help." 1>&2; exit 2; }
+
+# SYNOPSIS
+#   openUrl <url>
+# DESCRIPTION
+#   Opens the specified URL in the system's default browser.
+openUrl() {
+  local url=$1
+  open "$url" || { echo "Cannot locate or failed to open default browser; please go to '$url' manually." >&2; return 1; }
 }
 
-# Helper function for exiting with error message due to invalid parameters.
-#   dieSyntax [errMsg]
-# Default error message is provided, as is prefix and suffix; exit code is always 2.
-dieSyntax() {
-    echo "$kTHIS_NAME: PARAMETER ERROR: ${1:-"Invalid parameter(s) specified."} Use -h for help." 1>&2
-    exit 2
+# Prints the embedded Markdown-formatted man-page source to stdout.
+printManPageSource() {
+  sed -n -e $'/^: <<\'EOF_MAN_PAGE\'/,/^EOF_MAN_PAGE/ { s///; t\np;}' "$BASH_SOURCE"
 }
 
-# Output version number and exit, if requested. Note that the `ver="..."` statement is automatically updated by `make version VER=<newVer>` - DO keep the 'v' suffix in the variable _definition_.
-[[ $1 == '--version' ]] && { ver="v0.1.8"; echo "$kTHIS_NAME version ${ver#v}"; exit 0; }
+# Opens the man page, if installed; otherwise, tries to display the embedded Markdown-formatted man-page source; if all else fails: tries to display the man page online.
+openManPage() {
+  local pager embeddedText 
+  if ! man 1 "$kTHIS_NAME" 2>/dev/null; then
+    # 2nd attempt: if present, display the embedded Markdown-formatted man-page source
+    embeddedText=$(printManPageSource)
+    if [[ -n $embeddedText ]]; then
+      pager='more'
+      command -v less &>/dev/null && pager='less' # see if the non-standard `less` is available, because it's preferable to the POSIX utility `more`
+      printf '%s\n' "$embeddedText" | "$pager"
+    else # 3rd attempt: open the the man page on the utility's website
+      openUrl "${kTHIS_HOMEPAGE}/doc/${kTHIS_NAME}.md"
+    fi
+  fi  
+}
 
-# Command-line help.
-if [[ "$1" == '--help' || "$1" == '-h' ]]; then
-    cat <<EOF
+# Prints the contents of the synopsis chapter of the embedded Markdown-formatted man-page source.
+printUsage() {
+  local embeddedText
+  # Extract usage information from the SYNOPSIS chapter of the embedded Markdown-formatted man-page source.
+  embeddedText=$(sed -n -e $'/^: <<\'EOF_MAN_PAGE\'/,/^EOF_MAN_PAGE/!d; /SYNOPSIS$/,/^[^ ]/{ s///; t\np; }' "$BASH_SOURCE")
+  if [[ -n $embeddedText ]]; then
+    # Print extracted synopsis chapter - remove backticks for uncluttered display.
+    printf '%s\n' "$embeddedText" | tr -d '`'
+  else # No SYNOPIS chapter found; fall back to displaying the man page.
+    echo "WARNING: usage information not found; opening man page instead." >&2
+    openManPage
+  fi
+}
 
-SYNOPSIS:
-  $kTHIS_NAME [-w] [-s settings] [-t title] [-g|-G] [-d dir] [command [param1 ...]]
+# --- End: STANDARD HELPER FUNCTIONS
 
-DESCRIPTION:
-  Opens a new Terminal.app tab and optionally executes a
-  command and assigns settings, among other options.
+# ---  PROCESS STANDARD, OUTPUT-INFO-THEN-EXIT OPTIONS.
+case $1 in
+  --version)
+    # Output version number and exit, if requested.
+    echo "$kTHIS_NAME $kTHIS_VERSION"$'\nFor license information and more, visit '"$kTHIS_HOMEPAGE"; exit 0
+    ;;
+  -h|--help)
+    # Print usage information and exit.
+    printUsage; exit
+    ;;
+  --man)
+    # Display the manual page and exit, falling back to printing the embedded man-page source.
+    openManPage; exit
+    ;;
+  --man-embedded) # private option, used by `make update-doc`
+    # Print raw, embedded Markdown-formatted man-page source and exit
+    printManPageSource; exit
+    ;;
+  --home)
+    # Open the home page and exit.
+    openUrl "$kTHIS_HOMEPAGE"; exit
+    ;;
+esac
 
-  IMPORTANT: *Terminal.app must be allowed assistive access* in order for this
-  utility to work, which requires one-time authorization with administrative
-  privileges. If you get error messages instead of being prompted, authorize
-  Terminal.app via System Preferences > Security & Privacy > Privacy >
-  Accessibility.
-
-  The new tab will run a login shell (i.e., load the user's shell profile)
-  and by default inherit the working directory from the parent shell.
-
-  -w
-    creates the new tab in a new window rather than in Terminal's front
-    window.
-  -s
-    specifies the settings (profiles) to apply to the new tab, as
-    defined in Terminal.app's Preferences > Profiles, such as 'Grass';
-    settings determine the appearance and behavior of the new tab; name
-    matching is case-insensitive.
-  -t 
-    specifies a custom title to assign to the new tab; otherwise, if a 
-    command is specified, its first token will become the new tab's title.
-  -d
-    explicitly specifies a working directory for the new tab; by default, the
-    invoking shell's working directory is inherited (even if -w is also
-    specified).
-  -g
-    (back*g*round) causes Terminal not to activate, if it isn't the frontmost
-    application); within Terminal, however, the new tab will become active
-    active tab; useful in scripts that launch other applications and
-    don't want Terminal to steal focus later.
-  -G
-    causes Terminal not to activate *and* the active element within Terminal
-    not to change; i.e., the active window and tab stay the same. If Terminal
-    happens to be fronmost, the new tab will effectively open in the
-    background.
-
-  NOTE: With -g or -G specified, for technical reasons, Terminal / the new
-        tab will still activate *briefly, temporarily* in most scenarios.
-
-  Quoted parameters are handled properly and there's no need to quote the
-  command as a whole, provided it is a *single* command.
-  Prefix such a single command with 'exec' to automatically close the tab
-  when the command terminates, assuming the tab's settings are configured to
-  close the tab on termination of the shell.
-
-  To specify *multiple* commands, use 'eval' followed by a single,
-  *double*-quoted string in which the commands are separated by ';' Do NOT
-  use backslash-escaped double quotes *inside this string*; rather, use
-  *single-character backslash-escaping* as needed. Use 'exit' as the last
-  command to automatically close the tab when the command terminates,
-  assuming the tab's settings are configured to close the tab on termination
-  of the shell.
-  Precede 'exit' with 'read -s -n 1' to wait for a keystroke first.
-
-EXAMPLES:
-  # Create new tab with title 'Green' using settings 'Grass'
-  $kTHIS_NAME -t Green -s Grass  
-  $kTHIS_NAME ls -l "\$HOME/Library/Application Support"
-  $kTHIS_NAME -d "\$HOME/Library/Application Support" ls -1
-  $kTHIS_NAME /path/to/someScript arg1 arg2
-  # Execute a script and close the tab on termination (settings permitting).
-  $kTHIS_NAME exec /path/to/someScript arg1 arg2
-  # Pass a multi-command string via 'eval', wait for keystroke, then exit.
-  $kTHIS_NAME eval "ls \\\$HOME/Library/Application\ Support; 
-                    echo Press a key to exit.; read -s -n 1; exit"
-
-EOF
-    exit 0
-fi
+# --- MAIN BODY
 
 # Undocumented debugging support: if the very first argument is --dry-run, we print out the synthesized AppleScript rather than executing it.
 printScript=0 dryRun=0
@@ -242,8 +222,14 @@ fi
 
   # Synthesize the full shell command.
 if [[ -n $quotedShellCmds ]]; then
-      # Pass the commands as a single, double-quoted string, but escape all backslashes again (by doubling them), because AppleScript expects that.
-  CMD_CUSTOM="do script \"${quotedShellCmds//\\/\\\\}\" in newTab"
+  # Pass the commands as a single AppleScript string, of necessity double-quoted.
+  # For the benefit of AppleScript
+  #  - embedded backslashes must be escaped by doubling them
+  #  - embedded doubleq quotes must be backlash-escaped
+  quotedShellCmdsForAppleScript=${quotedShellCmds//\\/\\\\}
+  quotedShellCmdsForAppleScript=${quotedShellCmdsForAppleScript//\"/\\\"}
+  CMD_CUSTOM="do script \"${quotedShellCmdsForAppleScript}\" in newTab"
+  # CMD_CUSTOM="do script \"${quotedShellCmds//\\/\\\\}\" in newTab"
 fi
 
 if [[ -n $tabTitle ]]; then
@@ -271,3 +257,159 @@ EOF
 
 # Execute the AppleScript
 osascript <<<"$script"
+
+####
+# MAN PAGE MARKDOWN SOURCE
+#  - Place a Markdown-formatted version of the man page for this script
+#    below the : <<'EOF_MAN_PAGE' line below.
+#  - The entire rest of this script
+#    is assumed to be the Markdown document.
+#  Markdown formatting:
+#   - Append the manual-section number directly to the CLI name in the first heading; e.g.
+#      # foo(1) - does bar
+#   - Use 1-space indentation for plain-text rendering; 4-space indentation, as usual, for code blocks.
+#   - The contents of the SYNOPSIS chapter is extracted when -h/--help is invoked.
+#     Use 4-space indentation without markup for both the syntax line and the
+#     block of brief option descriptions; represent option-arguments and operands
+#     in angle brackets; e.g., '<foo>'
+#  - To support plain-text rendering in the terminal, limit lines to 80 chars.,
+#    and, for similar rendering as HTML, *end every line with 2 trailing spaces*.
+#  - Options list:
+#    - End every list item (bullet point) itself with 2 trailing spaces so
+#      that it renders on its own line.
+#    - To associate more than 1 paragraph with a list item, use the following TRICK:
+#      To produce an empty line while still keeping the text attached to the list item,
+#      use '&nbsp;<space><space>', though note that that introduces noise in plain-text rendering.
+#    - To follow the last list item with regular paragraphs, leave *2* empty lines
+#      in between.
+#   Character-styling markup in `man` view:
+#      `...` and **...** render as bolded (red) text
+#      _..._ and *...* render as word-individually underlined text
+####
+: <<'EOF_MAN_PAGE' # DO NOT ALTER THIS LINE.
+# ttab(1) - open a new Terminal.app tab or window
+
+## SYNOPSIS
+ Opens a new terminal tab or window in OS X's Terminal.app application.
+
+    ttab [-w] [-s <settings>] [-t <title>] [-g|-G] [-d <dir>] [<cmd> [<arg>...]]
+
+    -w                  open new tab in new terminal window
+    -s <settings>       assign a Terminal.app settings set (profile)
+    -t <title>          specify title for new tab
+    -g                  create tab in background (do not activate Terminal.app)
+    -G                  create tab in background and do not activate new tab
+    -d <dir>            specify working directory
+    <cmd> [<arg>...]    command to execute in the new tab
+
+ Standard options: `--help`, `--man`, `--version`, `--home`
+
+## DESCRIPTION
+ `ttab` opens a new Terminal.app tab with a variety of options, including  
+ executing a command in the new tab, assigning a title and working directory,  
+ and opening the tab in a new window.
+
+ IMPORTANT: **Terminal.app must be allowed assistive access** in order for this  
+ utility to work, which requires one-time authorization with administrative  
+ privileges. If you get error messages instead of being prompted, authorize  
+ Terminal.app via System Preferences > Security & Privacy > Privacy >  
+ Accessibility.
+
+ The new tab will run a login shell (i.e., load the user's shell profile)  
+ and by default inherit the working directory from the parent shell.
+
+ When specifying a command to execute in the new tab, quoted parameters are  
+ handled properly and there's no need to quote the command as a whole,  
+ provided it is a *single* command.  
+ Prefix such a single command with `exec` to exit the shell after the command  
+ terminates. If the tab's settings are configured to close tabs on termination  
+ of the shell, the tab will close automatically.
+
+ To specify *multiple* commands, use `eval` followed by a single, quoted  
+ string containing the entire shell command line to execute; in the simplest  
+ case, enclose the string in single-quotes and use ';' to separate commands.  
+ Use `exit` as the last command to automatically close the tab when the  
+ command terminates, assuming the tab's settings are configured to close the  
+ tab on termination of the shell.  
+ Precede `exit` with `read -rsn 1` to wait for a keystroke first.
+
+## OPTIONS
+ * `-w`  
+    creates the new tab in a new window rather than in Terminal's front  
+    window.
+
+ * `-s <settings>`  
+    specifies the settings (profiles) to apply to the new tab, as  
+    defined in Terminal.app's Preferences > Profiles, such as 'Grass';  
+    settings determine the appearance and behavior of the new tab; name  
+    matching is case-insensitive.
+
+ * `-t <title>`   
+    specifies a custom title to assign to the new tab; otherwise, if a   
+    command is specified, its first token will become the new tab's title.
+
+ * `-d <dir>`  
+    explicitly specifies a working directory for the new tab; by default, the  
+    invoking shell's working directory is inherited (even if `-w` is also  
+    specified).
+
+ * `-g`  
+    (back*g*round) causes Terminal not to activate, if it isn't the frontmost  
+    application); within Terminal, however, the new tab will become active  
+    active tab; useful in scripts that launch other applications and  
+    don't want Terminal to steal focus later.
+
+ * `-G`  
+    causes Terminal not to activate *and* the active element within Terminal  
+    not to change; i.e., the active window and tab stay the same. If Terminal  
+    happens to be frontmost, the new tab will effectively open in the  
+    background.
+
+
+ NOTE: With `-g` or `-G` specified, for technical reasons, Terminal / the new  
+       tab will still activate *briefly, temporarily* in most scenarios.
+
+## STANDARD OPTIONS
+ All standard options provide information only.
+
+ * `-h, --help`  
+    Prints the contents of the synopsis chapter to stdout for quick reference.
+
+ * `--man`  
+    Displays this manual page, which is a helpful alternative to using `man`, 
+    if the manual page isn't installed.
+
+ * `--version`  
+    Prints version information.
+    
+ * `--home`  
+    Opens this utility's home page in the system's default web browser.
+
+## LICENSE
+ For license information and more, visit this utility's home page by running  
+ `ttab --home`.
+
+## EXAMPLES
+    # Open new tab in current terminal window:
+    ttab
+
+    # Open new tab in new terminal window:
+    ttab -w
+
+    # Open new tab with title 'Green' using settings 'Grass':
+    ttab -t Green -s Grass  
+
+    # Open new tab and execute a command in it:
+    ttab ls -l "$HOME/Library/Application Support"
+
+    # Open new tab with specified working dir. and execute a command in it:
+    ttab -d "$HOME/Library/Application Support" ls -l
+    
+    # Execute a command and exit.
+    # If configured via settings, also close the tab.
+    ttab exec /path/to/someprogram arg1 arg2
+    
+    # Pass a multi-command string via 'eval', wait for a keystroke, then exit.
+    ttab eval 'ls "$HOME/Library/Application Support";
+                                echo Press any key to exit; read -rsn 1; exit'
+EOF_MAN_PAGE
